In [22]:
import numpy as np
import pandas as pd

a = np.arange(0,6)
a.reshape(2,3)
a = np.insert(a,[1,6],[6,7])
a 

array([0, 6, 1, 2, 3, 4, 5, 7])

In [27]:
np.arange(-1,5.)

array([-1.,  1.,  3.])

In [52]:
df = pd.DataFrame({1:[1,2,3],2:[4,5,6],3:[7,8,9]},index=['a','b','c']).T
df.index=['a','b','c']
df.columns=[1,2,3]
df

1  2  3
a  1  2  3
b  4  5  6
c  7  8  9

In [54]:
ar = np.array([1,2,3,3])
ar



array([1, 2, 3, 3])

In [56]:

type(ar)

numpy.ndarray

In [64]:
market = pd.read_csv(r"C:\Users\kunal\college\dataset\market_data\Assignment-1_Data.csv",sep='\t')
market['BillNo'='536365']

SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='? (3171969996.py, line 2)